/**
 * Nitrozen API
 * The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the `Authorization` header:  ``` Authorization: Bearer YOUR_TOKEN_HERE ```  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a `api_rate_limit` value (requests per minute). When the limit is exceeded, the API returns a `429 Too Many Requests` response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept `page` and `per_page` query parameters. The response includes a `meta` object with pagination details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntryInput model module.
 * @module model/EntryInput
 * @version 1.0.0
 */
class EntryInput {
    /**
     * Constructs a new <code>EntryInput</code>.
     * @alias module:model/EntryInput
     * @param title {String} 
     * @param content {String} 
     * @param category {module:model/EntryInput.CategoryEnum} 
     */
    constructor(title, content, category) { 
        
        EntryInput.initialize(this, title, content, category);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, content, category) { 
        obj['title'] = title;
        obj['content'] = content;
        obj['category'] = category;
        obj['is_published'] = false;
    }

    /**
     * Constructs a <code>EntryInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntryInput} obj Optional instance to populate.
     * @return {module:model/EntryInput} The populated <code>EntryInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntryInput();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('is_published')) {
                obj['is_published'] = ApiClient.convertToType(data['is_published'], 'Boolean');
            }
            if (data.hasOwnProperty('published_at')) {
                obj['published_at'] = ApiClient.convertToType(data['published_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EntryInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EntryInput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EntryInput.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is a string
        if (data['category'] && !(typeof data['category'] === 'string' || data['category'] instanceof String)) {
            throw new Error("Expected the field `category` to be a primitive type in the JSON string but got " + data['category']);
        }

        return true;
    }


}

EntryInput.RequiredProperties = ["title", "content", "category"];

/**
 * @member {String} title
 */
EntryInput.prototype['title'] = undefined;

/**
 * @member {String} content
 */
EntryInput.prototype['content'] = undefined;

/**
 * @member {module:model/EntryInput.CategoryEnum} category
 */
EntryInput.prototype['category'] = undefined;

/**
 * @member {Boolean} is_published
 * @default false
 */
EntryInput.prototype['is_published'] = false;

/**
 * Defaults to current time if is_published is true and this is not set.
 * @member {Date} published_at
 */
EntryInput.prototype['published_at'] = undefined;





/**
 * Allowed values for the <code>category</code> property.
 * @enum {String}
 * @readonly
 */
EntryInput['CategoryEnum'] = {

    /**
     * value: "new"
     * @const
     */
    "new": "new",

    /**
     * value: "improvement"
     * @const
     */
    "improvement": "improvement",

    /**
     * value: "fix"
     * @const
     */
    "fix": "fix",

    /**
     * value: "announcement"
     * @const
     */
    "announcement": "announcement"
};



export default EntryInput;

