/**
 * Nitrozen API
 * The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the `Authorization` header:  ``` Authorization: Bearer YOUR_TOKEN_HERE ```  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a `api_rate_limit` value (requests per minute). When the limit is exceeded, the API returns a `429 Too Many Requests` response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept `page` and `per_page` query parameters. The response includes a `meta` object with pagination details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Entry from './Entry';

/**
 * The ProjectsProjectEntriesPost201Response model module.
 * @module model/ProjectsProjectEntriesPost201Response
 * @version 1.0.0
 */
class ProjectsProjectEntriesPost201Response {
    /**
     * Constructs a new <code>ProjectsProjectEntriesPost201Response</code>.
     * @alias module:model/ProjectsProjectEntriesPost201Response
     */
    constructor() { 
        
        ProjectsProjectEntriesPost201Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProjectsProjectEntriesPost201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProjectsProjectEntriesPost201Response} obj Optional instance to populate.
     * @return {module:model/ProjectsProjectEntriesPost201Response} The populated <code>ProjectsProjectEntriesPost201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectsProjectEntriesPost201Response();

            if (data.hasOwnProperty('data')) {
                obj['data'] = Entry.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProjectsProjectEntriesPost201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProjectsProjectEntriesPost201Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          Entry.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/Entry} data
 */
ProjectsProjectEntriesPost201Response.prototype['data'] = undefined;






export default ProjectsProjectEntriesPost201Response;

