/**
 * Nitrozen API
 * The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the `Authorization` header:  ``` Authorization: Bearer YOUR_TOKEN_HERE ```  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a `api_rate_limit` value (requests per minute). When the limit is exceeded, the API returns a `429 Too Many Requests` response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept `page` and `per_page` query parameters. The response includes a `meta` object with pagination details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Entry from './Entry';
import PaginationMeta from './PaginationMeta';

/**
 * The ProjectsProjectEntriesGet200Response model module.
 * @module model/ProjectsProjectEntriesGet200Response
 * @version 1.0.0
 */
class ProjectsProjectEntriesGet200Response {
    /**
     * Constructs a new <code>ProjectsProjectEntriesGet200Response</code>.
     * @alias module:model/ProjectsProjectEntriesGet200Response
     */
    constructor() { 
        
        ProjectsProjectEntriesGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProjectsProjectEntriesGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProjectsProjectEntriesGet200Response} obj Optional instance to populate.
     * @return {module:model/ProjectsProjectEntriesGet200Response} The populated <code>ProjectsProjectEntriesGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectsProjectEntriesGet200Response();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Entry]);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = PaginationMeta.constructFromObject(data['meta']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProjectsProjectEntriesGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProjectsProjectEntriesGet200Response</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                Entry.validateJSON(item);
            };
        }
        // validate the optional field `meta`
        if (data['meta']) { // data not null
          PaginationMeta.validateJSON(data['meta']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Entry>} data
 */
ProjectsProjectEntriesGet200Response.prototype['data'] = undefined;

/**
 * @member {module:model/PaginationMeta} meta
 */
ProjectsProjectEntriesGet200Response.prototype['meta'] = undefined;






export default ProjectsProjectEntriesGet200Response;

