/**
 * Nitrozen API
 * The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the `Authorization` header:  ``` Authorization: Bearer YOUR_TOKEN_HERE ```  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a `api_rate_limit` value (requests per minute). When the limit is exceeded, the API returns a `429 Too Many Requests` response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept `page` and `per_page` query parameters. The response includes a `meta` object with pagination details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Project model module.
 * @module model/Project
 * @version 1.0.0
 */
class Project {
    /**
     * Constructs a new <code>Project</code>.
     * @alias module:model/Project
     */
    constructor() { 
        
        Project.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Project</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Project} obj Optional instance to populate.
     * @return {module:model/Project} The populated <code>Project</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Project();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('custom_domain')) {
                obj['custom_domain'] = ApiClient.convertToType(data['custom_domain'], 'String');
            }
            if (data.hasOwnProperty('domain_verification_status')) {
                obj['domain_verification_status'] = ApiClient.convertToType(data['domain_verification_status'], 'String');
            }
            if (data.hasOwnProperty('entries_count')) {
                obj['entries_count'] = ApiClient.convertToType(data['entries_count'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Project</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Project</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['custom_domain'] && !(typeof data['custom_domain'] === 'string' || data['custom_domain'] instanceof String)) {
            throw new Error("Expected the field `custom_domain` to be a primitive type in the JSON string but got " + data['custom_domain']);
        }
        // ensure the json data is a string
        if (data['domain_verification_status'] && !(typeof data['domain_verification_status'] === 'string' || data['domain_verification_status'] instanceof String)) {
            throw new Error("Expected the field `domain_verification_status` to be a primitive type in the JSON string but got " + data['domain_verification_status']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
Project.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Project.prototype['name'] = undefined;

/**
 * @member {String} slug
 */
Project.prototype['slug'] = undefined;

/**
 * @member {String} description
 */
Project.prototype['description'] = undefined;

/**
 * @member {String} custom_domain
 */
Project.prototype['custom_domain'] = undefined;

/**
 * @member {module:model/Project.DomainVerificationStatusEnum} domain_verification_status
 */
Project.prototype['domain_verification_status'] = undefined;

/**
 * @member {Number} entries_count
 */
Project.prototype['entries_count'] = undefined;

/**
 * @member {Date} created_at
 */
Project.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Project.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>domain_verification_status</code> property.
 * @enum {String}
 * @readonly
 */
Project['DomainVerificationStatusEnum'] = {

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "verified"
     * @const
     */
    "verified": "verified",

    /**
     * value: "failed"
     * @const
     */
    "failed": "failed"
};



export default Project;

