/**
 * Nitrozen API
 * The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the `Authorization` header:  ``` Authorization: Bearer YOUR_TOKEN_HERE ```  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a `api_rate_limit` value (requests per minute). When the limit is exceeded, the API returns a `429 Too Many Requests` response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept `page` and `per_page` query parameters. The response includes a `meta` object with pagination details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsageLimits model module.
 * @module model/UsageLimits
 * @version 1.0.0
 */
class UsageLimits {
    /**
     * Constructs a new <code>UsageLimits</code>.
     * @alias module:model/UsageLimits
     */
    constructor() { 
        
        UsageLimits.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsageLimits</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsageLimits} obj Optional instance to populate.
     * @return {module:model/UsageLimits} The populated <code>UsageLimits</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsageLimits();

            if (data.hasOwnProperty('max_projects')) {
                obj['max_projects'] = ApiClient.convertToType(data['max_projects'], 'Number');
            }
            if (data.hasOwnProperty('max_entries_per_month')) {
                obj['max_entries_per_month'] = ApiClient.convertToType(data['max_entries_per_month'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsageLimits</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsageLimits</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} max_projects
 */
UsageLimits.prototype['max_projects'] = undefined;

/**
 * @member {Number} max_entries_per_month
 */
UsageLimits.prototype['max_entries_per_month'] = undefined;






export default UsageLimits;

