/**
 * Nitrozen API
 * The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the `Authorization` header:  ``` Authorization: Bearer YOUR_TOKEN_HERE ```  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a `api_rate_limit` value (requests per minute). When the limit is exceeded, the API returns a `429 Too Many Requests` response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept `page` and `per_page` query parameters. The response includes a `meta` object with pagination details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsageLimits from './UsageLimits';

/**
 * The Usage model module.
 * @module model/Usage
 * @version 1.0.0
 */
class Usage {
    /**
     * Constructs a new <code>Usage</code>.
     * @alias module:model/Usage
     */
    constructor() { 
        
        Usage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Usage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Usage} obj Optional instance to populate.
     * @return {module:model/Usage} The populated <code>Usage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Usage();

            if (data.hasOwnProperty('projects_count')) {
                obj['projects_count'] = ApiClient.convertToType(data['projects_count'], 'Number');
            }
            if (data.hasOwnProperty('entries_this_month')) {
                obj['entries_this_month'] = ApiClient.convertToType(data['entries_this_month'], 'Number');
            }
            if (data.hasOwnProperty('limits')) {
                obj['limits'] = UsageLimits.constructFromObject(data['limits']);
            }
            if (data.hasOwnProperty('plan_name')) {
                obj['plan_name'] = ApiClient.convertToType(data['plan_name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Usage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Usage</code>.
     */
    static validateJSON(data) {
        // validate the optional field `limits`
        if (data['limits']) { // data not null
          UsageLimits.validateJSON(data['limits']);
        }
        // ensure the json data is a string
        if (data['plan_name'] && !(typeof data['plan_name'] === 'string' || data['plan_name'] instanceof String)) {
            throw new Error("Expected the field `plan_name` to be a primitive type in the JSON string but got " + data['plan_name']);
        }

        return true;
    }


}



/**
 * @member {Number} projects_count
 */
Usage.prototype['projects_count'] = undefined;

/**
 * @member {Number} entries_this_month
 */
Usage.prototype['entries_this_month'] = undefined;

/**
 * @member {module:model/UsageLimits} limits
 */
Usage.prototype['limits'] = undefined;

/**
 * @member {String} plan_name
 */
Usage.prototype['plan_name'] = undefined;






export default Usage;

