/**
 * Nitrozen API
 * The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the `Authorization` header:  ``` Authorization: Bearer YOUR_TOKEN_HERE ```  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a `api_rate_limit` value (requests per minute). When the limit is exceeded, the API returns a `429 Too Many Requests` response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept `page` and `per_page` query parameters. The response includes a `meta` object with pagination details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserPlan model module.
 * @module model/UserPlan
 * @version 1.0.0
 */
class UserPlan {
    /**
     * Constructs a new <code>UserPlan</code>.
     * @alias module:model/UserPlan
     */
    constructor() { 
        
        UserPlan.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserPlan</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserPlan} obj Optional instance to populate.
     * @return {module:model/UserPlan} The populated <code>UserPlan</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserPlan();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('plan_type')) {
                obj['plan_type'] = ApiClient.convertToType(data['plan_type'], 'String');
            }
            if (data.hasOwnProperty('max_projects')) {
                obj['max_projects'] = ApiClient.convertToType(data['max_projects'], 'Number');
            }
            if (data.hasOwnProperty('max_entries_per_month')) {
                obj['max_entries_per_month'] = ApiClient.convertToType(data['max_entries_per_month'], 'Number');
            }
            if (data.hasOwnProperty('custom_domain_allowed')) {
                obj['custom_domain_allowed'] = ApiClient.convertToType(data['custom_domain_allowed'], 'Boolean');
            }
            if (data.hasOwnProperty('analytics_enabled')) {
                obj['analytics_enabled'] = ApiClient.convertToType(data['analytics_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('api_access_enabled')) {
                obj['api_access_enabled'] = ApiClient.convertToType(data['api_access_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('api_rate_limit')) {
                obj['api_rate_limit'] = ApiClient.convertToType(data['api_rate_limit'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserPlan</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserPlan</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['plan_type'] && !(typeof data['plan_type'] === 'string' || data['plan_type'] instanceof String)) {
            throw new Error("Expected the field `plan_type` to be a primitive type in the JSON string but got " + data['plan_type']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
UserPlan.prototype['id'] = undefined;

/**
 * @member {String} name
 */
UserPlan.prototype['name'] = undefined;

/**
 * @member {module:model/UserPlan.PlanTypeEnum} plan_type
 */
UserPlan.prototype['plan_type'] = undefined;

/**
 * @member {Number} max_projects
 */
UserPlan.prototype['max_projects'] = undefined;

/**
 * @member {Number} max_entries_per_month
 */
UserPlan.prototype['max_entries_per_month'] = undefined;

/**
 * @member {Boolean} custom_domain_allowed
 */
UserPlan.prototype['custom_domain_allowed'] = undefined;

/**
 * @member {Boolean} analytics_enabled
 */
UserPlan.prototype['analytics_enabled'] = undefined;

/**
 * @member {Boolean} api_access_enabled
 */
UserPlan.prototype['api_access_enabled'] = undefined;

/**
 * Maximum API requests per minute for this plan
 * @member {Number} api_rate_limit
 */
UserPlan.prototype['api_rate_limit'] = undefined;





/**
 * Allowed values for the <code>plan_type</code> property.
 * @enum {String}
 * @readonly
 */
UserPlan['PlanTypeEnum'] = {

    /**
     * value: "free"
     * @const
     */
    "free": "free",

    /**
     * value: "subscription"
     * @const
     */
    "subscription": "subscription",

    /**
     * value: "lifetime"
     * @const
     */
    "lifetime": "lifetime"
};



export default UserPlan;

