/**
 * Nitrozen API
 * The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the `Authorization` header:  ``` Authorization: Bearer YOUR_TOKEN_HERE ```  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a `api_rate_limit` value (requests per minute). When the limit is exceeded, the API returns a `429 Too Many Requests` response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept `page` and `per_page` query parameters. The response includes a `meta` object with pagination details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import TokensGet200Response from '../model/TokensGet200Response';
import TokensPost201Response from '../model/TokensPost201Response';
import TokensPostRequest from '../model/TokensPostRequest';
import ValidationError from '../model/ValidationError';

/**
* Authentication service.
* @module api/AuthenticationApi
* @version 1.0.0
*/
export default class AuthenticationApi {

    /**
    * Constructs a new AuthenticationApi. 
    * @alias module:api/AuthenticationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the tokensGet operation.
     * @callback module:api/AuthenticationApi~tokensGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TokensGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List API tokens
     * Returns all API tokens for the authenticated user. Token values are not included.
     * @param {module:api/AuthenticationApi~tokensGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TokensGet200Response}
     */
    tokensGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TokensGet200Response;
      return this.apiClient.callApi(
        '/tokens', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the tokensPost operation.
     * @callback module:api/AuthenticationApi~tokensPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TokensPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create an API token
     * Creates a new API token. The plain-text token is only returned in this response and cannot be retrieved later. 
     * @param {module:model/TokensPostRequest} tokensPostRequest 
     * @param {module:api/AuthenticationApi~tokensPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TokensPost201Response}
     */
    tokensPost(tokensPostRequest, callback) {
      let postBody = tokensPostRequest;
      // verify the required parameter 'tokensPostRequest' is set
      if (tokensPostRequest === undefined || tokensPostRequest === null) {
        throw new Error("Missing the required parameter 'tokensPostRequest' when calling tokensPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TokensPost201Response;
      return this.apiClient.callApi(
        '/tokens', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the tokensTokenDelete operation.
     * @callback module:api/AuthenticationApi~tokensTokenDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Revoke an API token
     * Permanently revokes an API token. Any requests using this token will be rejected.
     * @param {Number} token Token ID
     * @param {module:api/AuthenticationApi~tokensTokenDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    tokensTokenDelete(token, callback) {
      let postBody = null;
      // verify the required parameter 'token' is set
      if (token === undefined || token === null) {
        throw new Error("Missing the required parameter 'token' when calling tokensTokenDelete");
      }

      let pathParams = {
        'token': token
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/tokens/{token}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
