/**
 * Nitrozen API
 * The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the `Authorization` header:  ``` Authorization: Bearer YOUR_TOKEN_HERE ```  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a `api_rate_limit` value (requests per minute). When the limit is exceeded, the API returns a `429 Too Many Requests` response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept `page` and `per_page` query parameters. The response includes a `meta` object with pagination details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EntryInput from '../model/EntryInput';
import ProjectsProjectEntriesGet200Response from '../model/ProjectsProjectEntriesGet200Response';
import ProjectsProjectEntriesPost201Response from '../model/ProjectsProjectEntriesPost201Response';
import ValidationError from '../model/ValidationError';

/**
* Entries service.
* @module api/EntriesApi
* @version 1.0.0
*/
export default class EntriesApi {

    /**
    * Constructs a new EntriesApi. 
    * @alias module:api/EntriesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the projectsProjectEntriesEntryDelete operation.
     * @callback module:api/EntriesApi~projectsProjectEntriesEntryDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete an entry
     * Permanently deletes a changelog entry.
     * @param {Number} project Project ID
     * @param {Number} entry Entry ID
     * @param {module:api/EntriesApi~projectsProjectEntriesEntryDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    projectsProjectEntriesEntryDelete(project, entry, callback) {
      let postBody = null;
      // verify the required parameter 'project' is set
      if (project === undefined || project === null) {
        throw new Error("Missing the required parameter 'project' when calling projectsProjectEntriesEntryDelete");
      }
      // verify the required parameter 'entry' is set
      if (entry === undefined || entry === null) {
        throw new Error("Missing the required parameter 'entry' when calling projectsProjectEntriesEntryDelete");
      }

      let pathParams = {
        'project': project,
        'entry': entry
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/projects/{project}/entries/{entry}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the projectsProjectEntriesEntryGet operation.
     * @callback module:api/EntriesApi~projectsProjectEntriesEntryGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ProjectsProjectEntriesPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get an entry
     * Returns a single entry by ID.
     * @param {Number} project Project ID
     * @param {Number} entry Entry ID
     * @param {module:api/EntriesApi~projectsProjectEntriesEntryGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ProjectsProjectEntriesPost201Response}
     */
    projectsProjectEntriesEntryGet(project, entry, callback) {
      let postBody = null;
      // verify the required parameter 'project' is set
      if (project === undefined || project === null) {
        throw new Error("Missing the required parameter 'project' when calling projectsProjectEntriesEntryGet");
      }
      // verify the required parameter 'entry' is set
      if (entry === undefined || entry === null) {
        throw new Error("Missing the required parameter 'entry' when calling projectsProjectEntriesEntryGet");
      }

      let pathParams = {
        'project': project,
        'entry': entry
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ProjectsProjectEntriesPost201Response;
      return this.apiClient.callApi(
        '/projects/{project}/entries/{entry}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the projectsProjectEntriesEntryPut operation.
     * @callback module:api/EntriesApi~projectsProjectEntriesEntryPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ProjectsProjectEntriesPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update an entry
     * Updates an existing changelog entry.
     * @param {Number} project Project ID
     * @param {Number} entry Entry ID
     * @param {module:model/EntryInput} entryInput 
     * @param {module:api/EntriesApi~projectsProjectEntriesEntryPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ProjectsProjectEntriesPost201Response}
     */
    projectsProjectEntriesEntryPut(project, entry, entryInput, callback) {
      let postBody = entryInput;
      // verify the required parameter 'project' is set
      if (project === undefined || project === null) {
        throw new Error("Missing the required parameter 'project' when calling projectsProjectEntriesEntryPut");
      }
      // verify the required parameter 'entry' is set
      if (entry === undefined || entry === null) {
        throw new Error("Missing the required parameter 'entry' when calling projectsProjectEntriesEntryPut");
      }
      // verify the required parameter 'entryInput' is set
      if (entryInput === undefined || entryInput === null) {
        throw new Error("Missing the required parameter 'entryInput' when calling projectsProjectEntriesEntryPut");
      }

      let pathParams = {
        'project': project,
        'entry': entry
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ProjectsProjectEntriesPost201Response;
      return this.apiClient.callApi(
        '/projects/{project}/entries/{entry}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the projectsProjectEntriesGet operation.
     * @callback module:api/EntriesApi~projectsProjectEntriesGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ProjectsProjectEntriesGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List entries
     * Returns entries for a project with optional filtering and pagination.
     * @param {Number} project Project ID
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [category] Filter by category
     * @param {module:model/String} [status] Filter by publish status
     * @param {Number} [page = 1)] Page number
     * @param {Number} [perPage = 15)] Items per page
     * @param {module:api/EntriesApi~projectsProjectEntriesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ProjectsProjectEntriesGet200Response}
     */
    projectsProjectEntriesGet(project, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'project' is set
      if (project === undefined || project === null) {
        throw new Error("Missing the required parameter 'project' when calling projectsProjectEntriesGet");
      }

      let pathParams = {
        'project': project
      };
      let queryParams = {
        'category': opts['category'],
        'status': opts['status'],
        'page': opts['page'],
        'per_page': opts['perPage']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ProjectsProjectEntriesGet200Response;
      return this.apiClient.callApi(
        '/projects/{project}/entries', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the projectsProjectEntriesPost operation.
     * @callback module:api/EntriesApi~projectsProjectEntriesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ProjectsProjectEntriesPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create an entry
     * Creates a new changelog entry. Set `is_published` to `true` to publish immediately. If `published_at` is not provided for a published entry, it defaults to the current time. 
     * @param {Number} project Project ID
     * @param {module:model/EntryInput} entryInput 
     * @param {module:api/EntriesApi~projectsProjectEntriesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ProjectsProjectEntriesPost201Response}
     */
    projectsProjectEntriesPost(project, entryInput, callback) {
      let postBody = entryInput;
      // verify the required parameter 'project' is set
      if (project === undefined || project === null) {
        throw new Error("Missing the required parameter 'project' when calling projectsProjectEntriesPost");
      }
      // verify the required parameter 'entryInput' is set
      if (entryInput === undefined || entryInput === null) {
        throw new Error("Missing the required parameter 'entryInput' when calling projectsProjectEntriesPost");
      }

      let pathParams = {
        'project': project
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ProjectsProjectEntriesPost201Response;
      return this.apiClient.callApi(
        '/projects/{project}/entries', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
