/**
 * Nitrozen API
 * The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the `Authorization` header:  ``` Authorization: Bearer YOUR_TOKEN_HERE ```  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a `api_rate_limit` value (requests per minute). When the limit is exceeded, the API returns a `429 Too Many Requests` response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept `page` and `per_page` query parameters. The response includes a `meta` object with pagination details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import PublicProjectsSlugEntriesGet200Response from '../model/PublicProjectsSlugEntriesGet200Response';

/**
* Public service.
* @module api/PublicApi
* @version 1.0.0
*/
export default class PublicApi {

    /**
    * Constructs a new PublicApi. 
    * @alias module:api/PublicApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the publicProjectsSlugEntriesGet operation.
     * @callback module:api/PublicApi~publicProjectsSlugEntriesGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PublicProjectsSlugEntriesGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List published entries (public)
     * Returns all published entries for a project. No authentication required.
     * @param {String} slug Project slug
     * @param {module:api/PublicApi~publicProjectsSlugEntriesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PublicProjectsSlugEntriesGet200Response}
     */
    publicProjectsSlugEntriesGet(slug, callback) {
      let postBody = null;
      // verify the required parameter 'slug' is set
      if (slug === undefined || slug === null) {
        throw new Error("Missing the required parameter 'slug' when calling publicProjectsSlugEntriesGet");
      }

      let pathParams = {
        'slug': slug
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PublicProjectsSlugEntriesGet200Response;
      return this.apiClient.callApi(
        '/public/projects/{slug}/entries', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
