/**
 * Nitrozen API
 * The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the `Authorization` header:  ``` Authorization: Bearer YOUR_TOKEN_HERE ```  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a `api_rate_limit` value (requests per minute). When the limit is exceeded, the API returns a `429 Too Many Requests` response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept `page` and `per_page` query parameters. The response includes a `meta` object with pagination details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NitrozenApi);
  }
}(this, function(expect, NitrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NitrozenApi.UserPlan();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserPlan', function() {
    it('should create an instance of UserPlan', function() {
      // uncomment below and update the code to test UserPlan
      //var instance = new NitrozenApi.UserPlan();
      //expect(instance).to.be.a(NitrozenApi.UserPlan);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new NitrozenApi.UserPlan();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new NitrozenApi.UserPlan();
      //expect(instance).to.be();
    });

    it('should have the property planType (base name: "plan_type")', function() {
      // uncomment below and update the code to test the property planType
      //var instance = new NitrozenApi.UserPlan();
      //expect(instance).to.be();
    });

    it('should have the property maxProjects (base name: "max_projects")', function() {
      // uncomment below and update the code to test the property maxProjects
      //var instance = new NitrozenApi.UserPlan();
      //expect(instance).to.be();
    });

    it('should have the property maxEntriesPerMonth (base name: "max_entries_per_month")', function() {
      // uncomment below and update the code to test the property maxEntriesPerMonth
      //var instance = new NitrozenApi.UserPlan();
      //expect(instance).to.be();
    });

    it('should have the property customDomainAllowed (base name: "custom_domain_allowed")', function() {
      // uncomment below and update the code to test the property customDomainAllowed
      //var instance = new NitrozenApi.UserPlan();
      //expect(instance).to.be();
    });

    it('should have the property analyticsEnabled (base name: "analytics_enabled")', function() {
      // uncomment below and update the code to test the property analyticsEnabled
      //var instance = new NitrozenApi.UserPlan();
      //expect(instance).to.be();
    });

    it('should have the property apiAccessEnabled (base name: "api_access_enabled")', function() {
      // uncomment below and update the code to test the property apiAccessEnabled
      //var instance = new NitrozenApi.UserPlan();
      //expect(instance).to.be();
    });

    it('should have the property apiRateLimit (base name: "api_rate_limit")', function() {
      // uncomment below and update the code to test the property apiRateLimit
      //var instance = new NitrozenApi.UserPlan();
      //expect(instance).to.be();
    });

  });

}));
