/**
 * Nitrozen API
 * The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the `Authorization` header:  ``` Authorization: Bearer YOUR_TOKEN_HERE ```  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a `api_rate_limit` value (requests per minute). When the limit is exceeded, the API returns a `429 Too Many Requests` response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept `page` and `per_page` query parameters. The response includes a `meta` object with pagination details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import NitrozenError from './NitrozenError';
import Entry from './model/Entry';
import EntryInput from './model/EntryInput';
import Error from './model/Error';
import NewToken from './model/NewToken';
import PaginationMeta from './model/PaginationMeta';
import Project from './model/Project';
import ProjectInput from './model/ProjectInput';
import ProjectsGet200Response from './model/ProjectsGet200Response';
import ProjectsPost201Response from './model/ProjectsPost201Response';
import ProjectsProjectEntriesGet200Response from './model/ProjectsProjectEntriesGet200Response';
import ProjectsProjectEntriesPost201Response from './model/ProjectsProjectEntriesPost201Response';
import PublicProjectsSlugEntriesGet200Response from './model/PublicProjectsSlugEntriesGet200Response';
import TokenInfo from './model/TokenInfo';
import TokensGet200Response from './model/TokensGet200Response';
import TokensPost201Response from './model/TokensPost201Response';
import TokensPostRequest from './model/TokensPostRequest';
import Usage from './model/Usage';
import UsageLimits from './model/UsageLimits';
import User from './model/User';
import UserGet200Response from './model/UserGet200Response';
import UserPlan from './model/UserPlan';
import UserUsageGet200Response from './model/UserUsageGet200Response';
import ValidationError from './model/ValidationError';
import AuthenticationApi from './api/AuthenticationApi';
import EntriesApi from './api/EntriesApi';
import ProjectsApi from './api/ProjectsApi';
import PublicApi from './api/PublicApi';
import UsersApi from './api/UsersApi';


/**
* The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the &#x60;Authorization&#x60; header:  &#x60;&#x60;&#x60; Authorization: Bearer YOUR_TOKEN_HERE &#x60;&#x60;&#x60;  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a &#x60;api_rate_limit&#x60; value (requests per minute). When the limit is exceeded, the API returns a &#x60;429 Too Many Requests&#x60; response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept &#x60;page&#x60; and &#x60;per_page&#x60; query parameters. The response includes a &#x60;meta&#x60; object with pagination details. .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var NitrozenApi = require('index'); // See note below*.
* var xxxSvc = new NitrozenApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new NitrozenApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new NitrozenApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new NitrozenApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The NitrozenError class.
     * @property {module:NitrozenError}
     */
    NitrozenError,

    /**
     * The Entry model constructor.
     * @property {module:model/Entry}
     */
    Entry,

    /**
     * The EntryInput model constructor.
     * @property {module:model/EntryInput}
     */
    EntryInput,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The NewToken model constructor.
     * @property {module:model/NewToken}
     */
    NewToken,

    /**
     * The PaginationMeta model constructor.
     * @property {module:model/PaginationMeta}
     */
    PaginationMeta,

    /**
     * The Project model constructor.
     * @property {module:model/Project}
     */
    Project,

    /**
     * The ProjectInput model constructor.
     * @property {module:model/ProjectInput}
     */
    ProjectInput,

    /**
     * The ProjectsGet200Response model constructor.
     * @property {module:model/ProjectsGet200Response}
     */
    ProjectsGet200Response,

    /**
     * The ProjectsPost201Response model constructor.
     * @property {module:model/ProjectsPost201Response}
     */
    ProjectsPost201Response,

    /**
     * The ProjectsProjectEntriesGet200Response model constructor.
     * @property {module:model/ProjectsProjectEntriesGet200Response}
     */
    ProjectsProjectEntriesGet200Response,

    /**
     * The ProjectsProjectEntriesPost201Response model constructor.
     * @property {module:model/ProjectsProjectEntriesPost201Response}
     */
    ProjectsProjectEntriesPost201Response,

    /**
     * The PublicProjectsSlugEntriesGet200Response model constructor.
     * @property {module:model/PublicProjectsSlugEntriesGet200Response}
     */
    PublicProjectsSlugEntriesGet200Response,

    /**
     * The TokenInfo model constructor.
     * @property {module:model/TokenInfo}
     */
    TokenInfo,

    /**
     * The TokensGet200Response model constructor.
     * @property {module:model/TokensGet200Response}
     */
    TokensGet200Response,

    /**
     * The TokensPost201Response model constructor.
     * @property {module:model/TokensPost201Response}
     */
    TokensPost201Response,

    /**
     * The TokensPostRequest model constructor.
     * @property {module:model/TokensPostRequest}
     */
    TokensPostRequest,

    /**
     * The Usage model constructor.
     * @property {module:model/Usage}
     */
    Usage,

    /**
     * The UsageLimits model constructor.
     * @property {module:model/UsageLimits}
     */
    UsageLimits,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserGet200Response model constructor.
     * @property {module:model/UserGet200Response}
     */
    UserGet200Response,

    /**
     * The UserPlan model constructor.
     * @property {module:model/UserPlan}
     */
    UserPlan,

    /**
     * The UserUsageGet200Response model constructor.
     * @property {module:model/UserUsageGet200Response}
     */
    UserUsageGet200Response,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
    * The AuthenticationApi service constructor.
    * @property {module:api/AuthenticationApi}
    */
    AuthenticationApi,

    /**
    * The EntriesApi service constructor.
    * @property {module:api/EntriesApi}
    */
    EntriesApi,

    /**
    * The ProjectsApi service constructor.
    * @property {module:api/ProjectsApi}
    */
    ProjectsApi,

    /**
    * The PublicApi service constructor.
    * @property {module:api/PublicApi}
    */
    PublicApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
