/**
 * Nitrozen API
 * The Nitrozen API allows you to programmatically manage your changelog projects and entries.  ## Authentication  All authenticated endpoints require a Bearer token. Create an API token from your [API Tokens](/api-tokens) page, then include it in the `Authorization` header:  ``` Authorization: Bearer YOUR_TOKEN_HERE ```  ## Rate Limiting  API rate limits are determined by your plan. Each plan specifies a `api_rate_limit` value (requests per minute). When the limit is exceeded, the API returns a `429 Too Many Requests` response. Unauthenticated requests are limited to 60 requests per minute per IP address.  ## Pagination  List endpoints that support pagination accept `page` and `per_page` query parameters. The response includes a `meta` object with pagination details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NitrozenApi);
  }
}(this, function(expect, NitrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NitrozenApi.EntriesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EntriesApi', function() {
    describe('projectsProjectEntriesEntryDelete', function() {
      it('should call projectsProjectEntriesEntryDelete successfully', function(done) {
        //uncomment below and update the code to test projectsProjectEntriesEntryDelete
        //instance.projectsProjectEntriesEntryDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('projectsProjectEntriesEntryGet', function() {
      it('should call projectsProjectEntriesEntryGet successfully', function(done) {
        //uncomment below and update the code to test projectsProjectEntriesEntryGet
        //instance.projectsProjectEntriesEntryGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('projectsProjectEntriesEntryPut', function() {
      it('should call projectsProjectEntriesEntryPut successfully', function(done) {
        //uncomment below and update the code to test projectsProjectEntriesEntryPut
        //instance.projectsProjectEntriesEntryPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('projectsProjectEntriesGet', function() {
      it('should call projectsProjectEntriesGet successfully', function(done) {
        //uncomment below and update the code to test projectsProjectEntriesGet
        //instance.projectsProjectEntriesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('projectsProjectEntriesPost', function() {
      it('should call projectsProjectEntriesPost successfully', function(done) {
        //uncomment below and update the code to test projectsProjectEntriesPost
        //instance.projectsProjectEntriesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
